"""addfilemanagmentforecol

Revision ID: 0d8ca00e94ac
Revises: d4935bd88d12
Create Date: 2023-05-25 15:47:45.260008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8ca00e94ac'
down_revision = 'd4935bd88d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FILE', sa.Column('articleid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'FILE', 'ARTICLE', ['articleid'], ['article_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FILE', type_='foreignkey')
    op.drop_column('FILE', 'articleid')
    # ### end Alembic commands ###
