"""scorerecordaddcol

Revision ID: 0e548908cc97
Revises: 
Create Date: 2023-05-18 09:30:52.654524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e548908cc97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCORERECORD', sa.Column('answerid', sa.Integer(), nullable=True))
    op.add_column('SCORERECORD', sa.Column('readid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SCORERECORD', 'READRECORD', ['readid'], ['readid'])
    op.create_foreign_key(None, 'SCORERECORD', 'ANSWERRECORD', ['answerid'], ['recordid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SCORERECORD', type_='foreignkey')
    op.drop_constraint(None, 'SCORERECORD', type_='foreignkey')
    op.drop_column('SCORERECORD', 'readid')
    op.drop_column('SCORERECORD', 'answerid')
    # ### end Alembic commands ###
