"""scorerecordaddcol

Revision ID: a4bdf8dc46e6
Revises: 0e548908cc97
Create Date: 2023-05-18 10:12:45.594342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bdf8dc46e6'
down_revision = '0e548908cc97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCORERECORD', sa.Column('articleid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SCORERECORD', 'ARTICLE', ['articleid'], ['article_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SCORERECORD', type_='foreignkey')
    op.drop_column('SCORERECORD', 'articleid')
    # ### end Alembic commands ###
