"""setfileartiidcannull

Revision ID: a8a73893e806
Revises: 0d8ca00e94ac
Create Date: 2023-05-26 20:42:00.552390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8a73893e806'
down_revision = '0d8ca00e94ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FILE', 'articleid',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FILE', 'articleid',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
