"""setfiletype

Revision ID: cb8518a01a1a
Revises: cbfb89ada090
Create Date: 2023-05-29 15:23:57.412418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8518a01a1a'
down_revision = 'cbfb89ada090'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FILE', sa.Column('type', sa.CHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FILE', 'type')
    # ### end Alembic commands ###
