"""setfileinsertdate

Revision ID: cbfb89ada090
Revises: a8a73893e806
Create Date: 2023-05-28 16:22:44.899591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfb89ada090'
down_revision = 'a8a73893e806'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FILE', sa.Column('insertdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FILE', 'insertdate')
    # ### end Alembic commands ###
