"""addfilemanagment

Revision ID: d4935bd88d12
Revises: a4bdf8dc46e6
Create Date: 2023-05-25 15:46:11.409939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4935bd88d12'
down_revision = 'a4bdf8dc46e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
